"""add_a11y_event_remove_state_from_window_event

Revision ID: 0884b45e71e9
Revises: bb25e889ad71
Create Date: 2024-07-22 18:16:45.133921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '0884b45e71e9'
down_revision = 'bb25e889ad71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a11y_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('a11y_counter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['handle'], ['window_event.handle'], name=op.f('fk_a11y_event_handle_window_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_a11y_event'))
    )
    with op.batch_alter_table('window_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handle', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('a11y_counter', sa.Integer(), nullable=True))
        batch_op.drop_column('state')
        batch_op.drop_column('window_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('window_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('window_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('state', sqlite.JSON(), nullable=True))
        batch_op.drop_column('a11y_counter')
        batch_op.drop_column('handle')

    op.drop_table('a11y_event')
    # ### end Alembic commands ###
