"""add_scrubbed_columns

Revision ID: 186316d4f3ca
Revises: 2a8a241785f2
Create Date: 2024-04-26 02:23:19.422051

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "186316d4f3ca"
down_revision = "2a8a241785f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("action_event", schema=None) as batch_op:
        batch_op.add_column(sa.Column("scrubbed_text", sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column("scrubbed_canonical_text", sa.String(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("action_event", schema=None) as batch_op:
        batch_op.drop_column("scrubbed_canonical_text")
        batch_op.drop_column("scrubbed_text")

    # ### end Alembic commands ###
