"""add_a11y_event_remove_state_from_window_event

Revision ID: 54b42e4fd1a4
Revises: bb25e889ad71
Create Date: 2024-07-23 16:36:45.883878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import openadapt

# revision identifiers, used by Alembic.
revision = '54b42e4fd1a4'
down_revision = 'bb25e889ad71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('a11y_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', openadapt.models.ForceFloat(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('handle', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('counter', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['counter'], ['window_event.counter'], name=op.f('fk_a11y_event_counter_window_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_a11y_event'))
    )
    with op.batch_alter_table('window_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handle', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('counter', sa.Integer(), nullable=True))
        batch_op.drop_column('state')
        batch_op.drop_column('window_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('window_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('window_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('state', sqlite.JSON(), nullable=True))
        batch_op.drop_column('counter')
        batch_op.drop_column('handle')

    op.drop_table('a11y_event')
    # ### end Alembic commands ###
