"""add_a11y_event_remove_state_from_window

Revision ID: f9397786028d
Revises: 98505a067995
Create Date: 2024-10-21 23:15:25.932599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
import openadapt

# revision identifiers, used by Alembic.
revision = 'f9397786028d'
down_revision = '98505a067995'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', openadapt.models.ForceFloat(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('strategy_name', sa.String(), nullable=True),
    sa.Column('strategy_args', sa.JSON(), nullable=True),
    sa.Column('git_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_replay'))
    )
    op.create_table('a11y_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', openadapt.models.ForceFloat(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('handle', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['handle', 'timestamp'], ['window_event.handle', 'window_event.timestamp'], name=op.f('fk_a11y_event_handle_window_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_a11y_event'))
    )
    with op.batch_alter_table('window_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handle', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uix_handle_timestamp', ['handle', 'timestamp'])
        batch_op.drop_column('window_id')
        batch_op.drop_column('state')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('window_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('window_id', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('uix_handle_timestamp', type_='unique')
        batch_op.drop_column('handle')

    op.drop_table('a11y_event')
    op.drop_table('replay')
    # ### end Alembic commands ###
