name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      description: What behaviour was expected and what actually happened? Include screenshots and log output where useful.
      value: I expected ... but what actually happened was ... 
        [image to illustrate the issue]
        ```relevant log output```
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: What Operating System did you use and steps would we take to reproduce the behaviour?
      value: I use [macOS/Microsoft Windows].
        Steps: 
        1. Go to '...' 
        2. Click on '....' 
        3. Scroll down to '....' 
    validations:
      required: true
