"""Added example guard for LLM output in DemoReplayStrategy 

Revision ID: 12e0c784d0bd
Revises: 5139d7df38f6
Create Date: 2023-04-23 15:37:54.466694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e0c784d0bd'
down_revision = '5139d7df38f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
