"""add BrowserEvent.message

Revision ID: 1a19ce257672
Revises: 8713b142f5de
Create Date: 2023-08-28 17:01:07.703670

"""
import sqlalchemy as sa

from alembic import op
import openadapt

# revision identifiers, used by Alembic.
revision = "1a19ce257672"
down_revision = "8713b142f5de"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "browser_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "recording_timestamp",
            openadapt.models.ForceFloat(precision=10, scale=2, asdecimal=False),
            nullable=True,
        ),
        sa.Column("message", sa.JSON(), nullable=True),
        sa.Column(
            "timestamp",
            openadapt.models.ForceFloat(precision=10, scale=2, asdecimal=False),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["recording_timestamp"],
            ["recording.timestamp"],
            name=op.f("fk_browser_event_recording_timestamp_recording"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_browser_event")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("browser_event")
    # ### end Alembic commands ###
