"""add file signals

Revision ID: 2beb0b30e213
Revises: 104d4a614d95
Create Date: 2023-07-14 09:49:22.463838

"""
from alembic import op
import openadapt.models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2beb0b30e213'
down_revision = '104d4a614d95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', openadapt.models.ForceFloat(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('recording_timestamp', openadapt.models.ForceFloat(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recording_timestamp'], ['recording.timestamp'], name=op.f('fk_file_signal_recording_timestamp_recording')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_signal'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_signal')
    # ### end Alembic commands ###
