"""add PerformanceStat

Revision ID: 3c4c5ff48310
Revises: c74e250c04cc
Create Date: 2023-05-27 02:15:18.650413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c4c5ff48310'
down_revision = 'c74e250c04cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
