"""Add audio info

Revision ID: 3d3239ae4849
Revises: 104d4a614d95
Create Date: 2023-05-31 19:36:46.269697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3239ae4849'
down_revision = '104d4a614d95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flac_data', sa.LargeBinary(), nullable=True),
    sa.Column('transcribed_text', sa.String(), nullable=True),
    sa.Column('recording_timestamp', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('words_with_timestamps', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recording_timestamp'], ['recording.timestamp'], name=op.f('fk_audio_info_recording_timestamp_recording')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_info'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_info')
    # ### end Alembic commands ###
