"""Add new tables for audio info and files

Revision ID: 3d3239ae4849
Revises: 104d4a614d95
Create Date: 2023-05-31 19:36:46.269697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d3239ae4849'
down_revision = '104d4a614d95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_file'))
    )
    op.create_table('audio_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_timestamp', openadapt.models.ForceFloat(precision=10, scale=2, asdecimal=False), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['audio_file.id'], name=op.f('fk_audio_info_file_id_audio_file')),
    sa.ForeignKeyConstraint(['recording_timestamp'], ['recording.timestamp'], name=op.f('fk_audio_info_recording_timestamp_recording')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_info'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_info')
    op.drop_table('audio_file')
    # ### end Alembic commands ###
