"""Window.window_id

Revision ID: b2dc41850120
Revises: d63569e4fb90
Create Date: 2023-05-17 12:50:35.125610

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "b2dc41850120"
down_revision = "d63569e4fb90"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("window_event", schema=None) as batch_op:
        batch_op.add_column(sa.Column("window_id", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("window_event", schema=None) as batch_op:
        batch_op.drop_column("window_id")

    # ### end Alembic commands ###
