"""add recording performance stats

Revision ID: c74e250c04cc
Revises: 5139d7df38f6
Create Date: 2023-05-08 12:45:10.082401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74e250c04cc'
down_revision = '5139d7df38f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_timestamp', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_performance_stat'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_stat')
    # ### end Alembic commands ###
