#!/usr/bin/env python3
"""Render versions and compatibility from the exact platform BOM."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

COMPONENT_LABELS = {
    "launcher": "Launcher",
    "flow": "Flow",
    "capture": "Capture",
    "privacy": "Privacy",
    "types": "Types",
    "desktop": "Desktop",
    "agent": "Agent",
}
RUNTIME_LABELS = {
    "launcher_environment": "Launcher environment",
    "customer_runner": "Runner",
    "desktop_sidecar": "Desktop sidecar",
    "agent_bridge": "Agent bridge",
}


def version_rows(manifest: dict) -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    components = manifest.get("components", {})
    for role, label in COMPONENT_LABELS.items():
        component = components.get(role)
        if not isinstance(component, dict) or not isinstance(
            component.get("version"), str
        ):
            raise ValueError(f"manifest component {role!r} has no version")
        rows.append({"role": role, "label": label, "version": component["version"]})

    runtime_units = manifest.get("runtime_units", {})
    for role, label in RUNTIME_LABELS.items():
        unit = runtime_units.get(role)
        if not isinstance(unit, dict) or not isinstance(unit.get("version"), str):
            raise ValueError(f"manifest runtime unit {role!r} has no version")
        row = {"role": role, "label": label, "version": unit["version"]}
        closure = unit.get("resolved") or unit.get("selected")
        if isinstance(closure, dict):
            row["resolved"] = ", ".join(
                f"{package}=={version}" for package, version in sorted(closure.items())
            )
        rows.append(row)
    return rows


def _artifact_lines(component: dict) -> str:
    return "<br>".join(
        f"`{artifact['filename']}` `{artifact['sha256']}`"
        for artifact in component.get("artifacts", [])
    )


def render_markdown(manifest: dict) -> str:
    """Render the complete human-readable report from the exact BOM."""

    status = manifest.get("compatibility_status", {})
    selection = manifest.get("release_selection", {})
    lines = [
        "# OpenAdapt platform compatibility report",
        "",
        "<!-- Generated by scripts/render_platform_versions.py. Do not edit. -->",
        "",
        f"- Generated: `{manifest.get('generated_at')}`",
        f"- Release channel: **{manifest.get('release_channel')}**",
        f"- Selection: `{selection.get('mode')}`",
        f"- Compatibility: **{status.get('status')}**",
        f"- Signature: `{manifest.get('signature', {}).get('status')}`",
        "",
        "## Published components",
        "",
        "| Role | Package | Version | Release source reference | Published artifacts |",
        "|---|---|---:|---|---|",
    ]
    for role, component in manifest.get("components", {}).items():
        provenance = component.get("provenance", {})
        source = (
            f"[`{provenance.get('release_ref')}`]({provenance.get('url')})<br>"
            f"commit `{provenance.get('commit')}`<br>"
            f"tree `{provenance.get('tree')}`"
        )
        lines.append(
            f"| {role} | `{component.get('package')}` | "
            f"`{component.get('version')}` | {source} | "
            f"{_artifact_lines(component)} |"
        )

    lines.extend(
        [
            "",
            "## Runtime selections",
            "",
            "| Unit | Version | Selected or locked OpenAdapt packages |",
            "|---|---:|---|",
        ]
    )
    for role, unit in manifest.get("runtime_units", {}).items():
        closure = unit.get("resolved") or unit.get("selected") or {}
        selected = "<br>".join(
            f"`{package}=={version}`"
            for package, version in sorted(closure.items())
        )
        lines.append(f"| {role} | `{unit.get('version')}` | {selected} |")

    lines.extend(
        [
            "",
            "## Selected-platform dependency compatibility",
            "",
            "These edges show whether each selected integration version satisfies "
            "its published dependency constraint. Optional markers do not mean "
            "that every package is installed in every runtime unit.",
            "",
            "| Scope | Source | Target | Constraint | Selected | Activation |",
            "|---|---|---|---|---:|---|",
        ]
    )
    for edge in manifest.get("dependency_edges", []):
        activation = "<br>".join(
            f"`{value}`"
            for value in sorted(
                {row.get("marker") or "always" for row in edge.get("activations", [])}
            )
        )
        lines.append(
            f"| {edge.get('scope')} | `{edge.get('source_package')}=="
            f"{edge.get('source_version')}` | `{edge.get('target_package')}` | "
            f"`{edge.get('requires')}` | `{edge.get('resolved')}` | "
            f"{activation} |"
        )

    if status.get("failures"):
        lines.extend(["", "### Compatibility failures", ""])
        for failure in status["failures"]:
            lines.append(
                f"- `{failure.get('source_role')}` -> `{failure.get('package')}` "
                f"requires `{failure.get('requires')}`; the resolved version is "
                f"`{failure.get('resolved')}`."
            )

    lines.extend(
        [
            "",
            "## Cross-component schemas",
            "",
            "| Contract | Owner | Accepted versions | Exact source |",
            "|---|---|---|---|",
        ]
    )
    for name, schema in manifest.get("schema_compatibility", {}).items():
        prefix = schema.get("schema_prefix") or schema.get("schema_field")
        source = "<br>".join(
            f"[`{item.get('path')}`]({item.get('url')}) "
            f"`{item.get('sha256')}`"
            for item in schema.get("source_files", [])
        )
        lines.append(
            f"| `{name}` | `{schema.get('source_component')}` | "
            f"`{prefix}` {schema.get('accepted_versions')} | {source} |"
        )

    lines.extend(
        [
            "",
            "## Host operating systems",
            "",
            ", ".join(f"`{name}`" for name in manifest.get("supported_os", [])),
            "",
            "## Substrate delivery",
            "",
            "| Substrate | Public label | Delivery |",
            "|---|---|---|",
        ]
    )
    for substrate in manifest.get("substrate_drivers", []):
        lines.append(
            f"| {substrate.get('name')} | {substrate.get('public_label')} | "
            f"{substrate.get('delivery')} |"
        )

    lines.extend(["", "## Qualification evidence", ""])
    for evidence in manifest.get("qualification_evidence", []):
        location = evidence.get("url")
        if not location:
            location = (
                f"https://github.com/{evidence.get('repository')}/tree/"
                f"main/{evidence.get('path')}"
            )
        lines.append(
            f"- [{evidence.get('id')}]({location}): "
            f"{evidence.get('description')}"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest", type=Path, default=ROOT / "platform-manifest.json"
    )
    parser.add_argument(
        "--format", choices=("text", "json", "markdown"), default="text"
    )
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    try:
        manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
        rows = version_rows(manifest)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"FATAL: cannot render platform versions: {exc}", file=sys.stderr)
        return 1

    if args.format == "json":
        rendered = json.dumps(
            {
                "release_channel": manifest.get("release_channel"),
                "compatibility_status": manifest.get(
                    "compatibility_status", {}
                ).get("status"),
                "supported_os": manifest.get("supported_os", []),
                "substrates": manifest.get("substrate_drivers", []),
                "versions": rows,
            },
            indent=2,
        )
    elif args.format == "markdown":
        rendered = render_markdown(manifest)
    else:
        text_lines = [
            f"Release channel: {manifest.get('release_channel')}",
            f"Compatibility: {manifest.get('compatibility_status', {}).get('status')}",
        ]
        for row in rows:
            suffix = f" ({row['resolved']})" if row.get("resolved") else ""
            text_lines.append(f"{row['label']}: {row['version']}{suffix}")
        rendered = "\n".join(text_lines)

    if args.output:
        args.output.write_text(rendered.rstrip() + "\n", encoding="utf-8")
        print(f"Wrote {args.output}")
    else:
        print(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
