"""add_original_recording_id

Revision ID: 2a8a241785f2
Revises: 87a78a84a8bf
Create Date: 2024-04-25 10:25:54.685135

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "2a8a241785f2"
down_revision = "87a78a84a8bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recording", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("original_recording_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_recording_original_recording_id_recording"),
            "recording",
            ["original_recording_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recording", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_recording_original_recording_id_recording"),
            type_="foreignkey",
        )
        batch_op.drop_column("original_recording_id")

    # ### end Alembic commands ###
