"""generate_unique_user_id

Revision ID: bb25e889ad71
Revises: a29b537fabe6
Create Date: 2024-06-11 17:16:28.009900

"""
from uuid import uuid4
import json

from alembic import op
import sqlalchemy as sa

from openadapt.config import config

# revision identifiers, used by Alembic.
revision = "bb25e889ad71"
down_revision = "a29b537fabe6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    config.UNIQUE_USER_ID = str(uuid4())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    config.UNIQUE_USER_ID = ""
    # ### end Alembic commands ###
